/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

// Not exported
@interface ABCallback : NSObject
{
    id target;
    SEL selector;
    id info;
}

+ (id)callbackWithTarget:(id)arg1 selector:(SEL)arg2 info:(id)arg3;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 info:(id)arg3;
- (void)dealloc;
- (void)invoke:(id)arg1;
- (void)dissociateTarget;

@end

