/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@class NSString, NSURL;

// Not exported
@interface Twitlonger : NSObject
{
    NSString *identifier;
    NSURL *link;
    NSString *shortLink;
    NSString *content;
    NSString *username;
}

+ (id)applicationKey;
+ (void)post:(id)arg1 twitterUsername:(id)arg2 callback:(id)arg3;
+ (void)didPost:(id)arg1 info:(id)arg2;
- (void)parseXML:(id)arg1 info:(id)arg2;
@property(copy, nonatomic) NSString *username; // @synthesize username;
@property(copy, nonatomic) NSString *content; // @synthesize content;
@property(copy, nonatomic) NSString *shortLink; // @synthesize shortLink;
@property(copy, nonatomic) NSURL *link; // @synthesize link;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier;

@end

